#SPDX-License-Identifier: MIT-0
---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled

