#SPDX-License-Identifier: MIT-0
---
- name: Set Tomcat version
  set_fact:
    tomcat_version: 9.0.85
    tomcat_major_version: 9

- name: Create tomcat group
  group:
    name: tomcat

- name: Create tomcat user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    create_home: no

- name: Download Tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    mode: '0644'

- name: Create install directory
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: Extract Tomcat
  unarchive:
    src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]


