#SPDX-License-Identifier: MIT-0
---
- name: Install Memcached and libmemcached
  apt:
    name: 
      - memcached
      - libmemcached-tools
    state: present
    update_cache: yes

- name: Ensure Memcached is running
  service:
    name: memcached
    state: started
    enabled: yes

